spring:
  application:
    name: config-client
  rabbitmq:
    host: 192.168.1.9
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        springCloudBusInput: 
          group: -PropertyChanged-Consumer-
client:
  propA: foo
  propB: goo
  propC: joo_SUCCESS_OK
